Repository pittsfordrobotics/RapidReact2022, pull requests merged in 2022-02, with the labels that each got.

#3 Cleanup
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/Pathing.java
  src/main/java/frc/robot/subsystems/Drive.java
  src/main/java/frc/robot/subsystems/Limelight.java
Labels: enhancement

#5 Basic trajectory code + cleanup
  src/main/deploy/example.txt
  src/main/deploy/pathplanner/Test.path
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/AutoPathing.java
  src/main/java/frc/robot/commands/DriveResetOdometry.java
  src/main/java/frc/robot/commands/DriveZero.java
  src/main/java/frc/robot/subsystems/Drive.java
  vendordeps/PathplannerLib.json
  vendordeps/Phoenix.json
Labels: ready for testing

#4 Climber
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/ClimberDown.java
  src/main/java/frc/robot/commands/ClimberUp.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Drive.java
  src/main/java/frc/robot/util/LazySparkMax.java
Labels: work in progress, waiting for mechanical

#6 Rate limit
  build.gradle
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/AutoPathing.java
  src/main/java/frc/robot/commands/DriveXbox.java
  src/main/java/frc/robot/subsystems/Drive.java
  src/main/java/frc/robot/subsystems/Limelight.java
  src/main/java/frc/robot/util/controller/BetterXboxController.java
Labels: ready for testing
